image: alpine:3.6

stages:
  - test

.npm-install-alpine: &npm-install-alpine
  before_script:
    - PATH=$PATH:$CI_PROJECT_DIR/node_modules/.bin

htmlhint:
  image: node:7.2-alpine
  stage: test
  <<: *npm-install-alpine
  cache:
    key: "$CI_BUILD_NAME"
    paths:
      - node_modules/
    script:
      - npm install htmlhint --silent
      - cd public
      - htmlhint
    dependencies:
      - jekyll
    only:
      - branches@techmunchies/techmunchies.gitlab.io
    tags:
      - docker

